### ISSUE TITLE
Google Docs 문서

### ISSUE THREAD

**Issue by luncliff** [13th-kernelC/StudyNote#2]
### 문서 링크 관리

주간 링크는 URL로 추가해주세요
### 파일화

누적된 Google Docs문서를 정리하기에 앞서, 별도로 파일로 저장하는 것을 고려하기로 했습니다.

**Comment by jinsu-root** [comment]
160723 일자
https://docs.google.com/document/d/1xzDiJDNJckGF-07iONa5Rg8ySRyBgAPWOfEWpJdmNBY/edit?usp=sharing

**Comment by jinsu-root** [comment]
160730 일자
https://docs.google.com/document/d/1MmYcD5j2NhHGVjEwE-t6oH0x8CpGAOj5i__gcR1b9Io/edit?usp=sharing
